Refactor Jenkinsfile for improved build process

diff --git a/spring-boot-app/JenkinsFile b/spring-boot-app/JenkinsFile
--- a/spring-boot-app/JenkinsFile
+++ b/spring-boot-app/JenkinsFile
@@ -1,68 +1,99 @@
 pipeline {
-  agent {
-    docker {
-      image 'maven-docker-agent:v1'
-      args '--user root -v /var/run/docker.sock:/var/run/docker.sock' // mount Docker socket to access the host's Docker daemon
-    }
-  }
-  stages {
+agent {
+docker {
+image 'maven-docker-agent'
+args '--user root -v /var/run/docker.sock:/var/run/docker.sock'
+}
+}
+
+stages {
+
     stage('Checkout') {
-      steps {
-        sh 'echo passed'
-        //git branch: 'main', url: 'https://github.com/user/repo.git'
-      }
-    }
-    stage('Build and Test') {
-      steps {
-        sh 'ls -ltr'
-        // build the project and create a JAR file
-        sh 'cd java-maven-sonar-argocd/spring-boot-app && mvn clean package'
-      }
-    }
-    stage('Static Code Analysis') {
-      environment {
-        SONAR_URL = "http://54.238.224.46:9000"
-      }
-      steps {
-        withCredentials([string(credentialsId: 'sonarqube', variable: 'SONAR_AUTH_TOKEN')]) {
-          sh 'cd java-maven-sonar-argocd/spring-boot-app && mvn sonar:sonar -Dsonar.login=$SONAR_AUTH_TOKEN -Dsonar.host.url=${SONAR_URL}'
-        }
-      }
-    }
-    stage('Build and Push Docker Image') {
-      environment {
-        DOCKER_IMAGE = "the/ultimate-cicd:${BUILD_NUMBER}"
-        // DOCKERFILE_LOCATION = "java-maven-sonar-argocd/spring-boot-app/Dockerfile"
-        REGISTRY_CREDENTIALS = credentials('docker-cred')
-      }
-      steps {
-        script {
-            sh 'cd java-maven-sonar-argocd-helm-k8s/spring-boot-app && docker build -t ${DOCKER_IMAGE} .'
-            def dockerImage = docker.image("${DOCKER_IMAGE}")
-            docker.withRegistry('https://index.docker.io/v1/', "docker-cred") {
-                dockerImage.push()
-            }
-        }
-      }
-    }
-    stage('Update Deployment File') {
-        environment {
-            GIT_REPO_NAME = "Jenkins-repo"
-            GIT_USER_NAME = "username"
-        }
         steps {
-            withCredentials([string(credentialsId: 'github', variable: 'GITHUB_TOKEN')]) {
+            sh 'echo "Source code checked out successfully"'
+            sh 'pwd'
+            sh 'ls -ltr'
+        }
+    }
+
+    stage('Build and Test') {
+        steps {
+            sh '''
+                cd spring-boot-app
+                mvn clean package
+            '''
+        }
+    }
+
+    stage('Static Code Analysis') {
+        environment {
+            SONAR_URL = "http://54.238.224.46:9000"
+        }
+
+        steps {
+            withCredentials([string(credentialsId: 'sonarqube', variable: 'SONAR_AUTH_TOKEN')]) {
                 sh '''
-                    git config user.email "xyz@gmail.com"
-                    git config user.name "username"
-                    BUILD_NUMBER=${BUILD_NUMBER}
-                    sed -i "s/replaceImageTag/${BUILD_NUMBER}/g" java-maven-sonar-argocd-helm-k8s/spring-boot-app-manifests/deployment.yml
-                    git add java-maven-sonar-argocd-helm-k8s/spring-boot-app-manifests/deployment.yml
-                    git commit -m "Update deployment image to version ${BUILD_NUMBER}"
-                    git push https://${GITHUB_TOKEN}@github.com/${GIT_USER_NAME}/${GIT_REPO_NAME} HEAD:main
+                    cd spring-boot-app
+                    mvn sonar:sonar \
+                    -Dsonar.login=$SONAR_AUTH_TOKEN \
+                    -Dsonar.host.url=$SONAR_URL
                 '''
             }
         }
     }
-  }
+
+    stage('Build and Push Docker Image') {
+        environment {
+            DOCKER_IMAGE = "nimnajudy/ultimate-cicd:${BUILD_NUMBER}"
+        }
+
+        steps {
+            script {
+                sh """
+                    cd spring-boot-app
+                    docker build -t ${DOCKER_IMAGE} .
+                """
+
+                docker.withRegistry('https://index.docker.io/v1/', 'docker-cred') {
+                    docker.image("${DOCKER_IMAGE}").push()
+                }
+            }
+        }
+    }
+
+    stage('Update Deployment File') {
+        environment {
+            GIT_REPO_NAME = "java-maven-sonar-argocd"
+            GIT_USER_NAME = "nimnadev"
+        }
+
+        steps {
+            withCredentials([string(credentialsId: 'github', variable: 'GITHUB_TOKEN')]) {
+                sh """
+                    git config user.email "nimnaevz96@gmail.com"
+                    git config user.name "nimnadev"
+
+                    sed -i "s/replaceImageTag/${BUILD_NUMBER}/g" spring-boot-app-manifests/deployment.yml
+
+                    git add spring-boot-app-manifests/deployment.yml
+
+                    git commit -m "Update deployment image to version ${BUILD_NUMBER}" || true
+
+                    git push https://${GITHUB_TOKEN}@github.com/${GIT_USER_NAME}/${GIT_REPO_NAME}.git HEAD:main
+                """
+            }
+        }
+    }
 }
+
+post {
+    success {
+        echo 'Pipeline executed successfully!'
+    }
+
+    failure {
+        echo 'Pipeline failed!'
+    }
+}
+}
+
